FROM alpine:3.12

ENV USERNAME=fossil \
    FOSSIL_ARCH=x64 \
    FOSSIL_VERSION=2.11.1

RUN addgroup -Sg 400 $USERNAME \
  && adduser -Su 400 -G $USERNAME $USERNAME \
  && mkdir /fossils \
  && chown -R $USERNAME:$USERNAME /fossils \
  && apk add --no-cache curl \
  && curl -fLo /tmp/fossil.tar.gz https://www.fossil-scm.org/home/uv/fossil-linux-$FOSSIL_ARCH-$FOSSIL_VERSION.tar.gz \
  && tar xvf /tmp/fossil.tar.gz -C /opt \
  && rm /tmp/fossil.tar.gz \
  && apk del --purge --no-cache curl \
  && rm -f /var/cache/apk/*

VOLUME ["/fossils"]

WORKDIR ["/fossils"]

EXPOSE 8181

ENTRYPOINT ["/opt/fossil"]

CMD ["server","--repolist","--port","8181","--skin","ardoise","/fossils"]
